# Generated by stoatworks-unraid/scripts/gen-docker.mjs from fleet.json.
# Repo: caspar-av. Edit fleet.json and regenerate — direct edits are overwritten.
#
# caspar-AV — Rust service.
#
# NOTE: Two things a Rust-only Dockerfile gets wrong here. `web/` is NOT tracked in
# git — console/vite.config.ts builds into ../web with emptyOutDir — so the
# image needs a Node stage before the Rust one or it ships a server whose
# ServeDir points at nothing and 404s every page. And `--web` defaults to the
# relative path `web`, which resolves against the working directory, so the
# runtime stage passes an absolute /app/web rather than relying on WORKDIR.

# console/ builds into web/, which is NOT tracked in
# git. Without this stage the runtime has no UI to serve.
FROM node:22-slim AS web
WORKDIR /app
COPY . .
RUN cd console && npm ci && npm run build

FROM rust:1-slim AS builder
WORKDIR /app

# pkg-config and libssl-dev are not needed by the current dependency set (no
# openssl-sys in Cargo.lock), but cmake and a C toolchain are cheap insurance
# for transitive crates that build vendored C. Remove them if the build proves
# it does not need them.
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential cmake pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN cargo build --release -p showd

FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY --from=builder /app/target/release/caspar-avd /usr/local/bin/caspar-avd
COPY --from=web /app/web /app/web

EXPOSE 8080
VOLUME ["/app/data"]

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -fsS http://localhost:8080/ >/dev/null || exit 1

CMD ["caspar-avd", "--bind", "0.0.0.0:8080", "--web", "/app/web"]
